<?php

namespace Container2d5sZpy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z4zXMOYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z4zXMOY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z4zXMOY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'soutien' => ['privates', '.errored..service_locator.Z4zXMOY.App\\Entity\\Soutien', NULL, 'Cannot autowire service ".service_locator.Z4zXMOY": it needs an instance of "App\\Entity\\Soutien" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'soutien' => 'App\\Entity\\Soutien',
        ]);
    }
}
