<?php

namespace Container2d5sZpy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8AN_KR2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8AN.kR2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8AN.kR2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'revRepo' => ['privates', 'App\\Repository\\RevendicationRepository', 'getRevendicationRepositoryService', true],
        ], [
            'catRepo' => 'App\\Repository\\CategorieRepository',
            'revRepo' => 'App\\Repository\\RevendicationRepository',
        ]);
    }
}
