<?php

namespace ContainerZ33JWL3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendication2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tpTJ1Ks.App\Entity\Revendication' shared service.
     *
     * @return \App\Entity\Revendication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tpTJ1Ks": it needs an instance of "App\\Entity\\Revendication" but this type has been excluded in "config/services.yaml".');
    }
}
