<?php

namespace ContainerGqr12FD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FJGYS9EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FJGYS9E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FJGYS9E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\RevendicationController::delete' => ['privates', '.service_locator.YcJ.L7F', 'get_ServiceLocator_YcJ_L7FService', true],
            'App\\Controller\\RevendicationController::edit' => ['privates', '.service_locator.YcJ.L7F', 'get_ServiceLocator_YcJ_L7FService', true],
            'App\\Controller\\RevendicationController::index' => ['privates', '.service_locator.Rgogugj', 'get_ServiceLocator_RgogugjService', true],
            'App\\Controller\\RevendicationController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RevendicationController::show' => ['privates', '.service_locator.tpTJ1Ks', 'get_ServiceLocator_TpTJ1KsService', true],
            'App\\Controller\\SoutienController::delete' => ['privates', '.service_locator.Z4zXMOY', 'get_ServiceLocator_Z4zXMOYService', true],
            'App\\Controller\\SoutienController::edit' => ['privates', '.service_locator.Z4zXMOY', 'get_ServiceLocator_Z4zXMOYService', true],
            'App\\Controller\\SoutienController::index' => ['privates', '.service_locator.uj49irv', 'get_ServiceLocator_Uj49irvService', true],
            'App\\Controller\\SoutienController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SoutienController::show' => ['privates', '.service_locator.pynONhj', 'get_ServiceLocator_PynONhjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.aw9RHlF', 'get_ServiceLocator_Aw9RHlFService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.j7wOkYK', 'get_ServiceLocator_J7wOkYKService', true],
            'App\\Controller\\RevendicationController:delete' => ['privates', '.service_locator.YcJ.L7F', 'get_ServiceLocator_YcJ_L7FService', true],
            'App\\Controller\\RevendicationController:edit' => ['privates', '.service_locator.YcJ.L7F', 'get_ServiceLocator_YcJ_L7FService', true],
            'App\\Controller\\RevendicationController:index' => ['privates', '.service_locator.Rgogugj', 'get_ServiceLocator_RgogugjService', true],
            'App\\Controller\\RevendicationController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RevendicationController:show' => ['privates', '.service_locator.tpTJ1Ks', 'get_ServiceLocator_TpTJ1KsService', true],
            'App\\Controller\\SoutienController:delete' => ['privates', '.service_locator.Z4zXMOY', 'get_ServiceLocator_Z4zXMOYService', true],
            'App\\Controller\\SoutienController:edit' => ['privates', '.service_locator.Z4zXMOY', 'get_ServiceLocator_Z4zXMOYService', true],
            'App\\Controller\\SoutienController:index' => ['privates', '.service_locator.uj49irv', 'get_ServiceLocator_Uj49irvService', true],
            'App\\Controller\\SoutienController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SoutienController:show' => ['privates', '.service_locator.pynONhj', 'get_ServiceLocator_PynONhjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\RevendicationController::delete' => '?',
            'App\\Controller\\RevendicationController::edit' => '?',
            'App\\Controller\\RevendicationController::index' => '?',
            'App\\Controller\\RevendicationController::new' => '?',
            'App\\Controller\\RevendicationController::show' => '?',
            'App\\Controller\\SoutienController::delete' => '?',
            'App\\Controller\\SoutienController::edit' => '?',
            'App\\Controller\\SoutienController::index' => '?',
            'App\\Controller\\SoutienController::new' => '?',
            'App\\Controller\\SoutienController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\RevendicationController:delete' => '?',
            'App\\Controller\\RevendicationController:edit' => '?',
            'App\\Controller\\RevendicationController:index' => '?',
            'App\\Controller\\RevendicationController:new' => '?',
            'App\\Controller\\RevendicationController:show' => '?',
            'App\\Controller\\SoutienController:delete' => '?',
            'App\\Controller\\SoutienController:edit' => '?',
            'App\\Controller\\SoutienController:index' => '?',
            'App\\Controller\\SoutienController:new' => '?',
            'App\\Controller\\SoutienController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
