<?php

namespace ContainerGqr12FD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YcJ_L7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YcJ.L7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YcJ.L7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'revendication' => ['privates', '.errored..service_locator.YcJ.L7F.App\\Entity\\Revendication', NULL, 'Cannot autowire service ".service_locator.YcJ.L7F": it needs an instance of "App\\Entity\\Revendication" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'revendication' => 'App\\Entity\\Revendication',
        ]);
    }
}
