<?php

namespace Container51wFsbP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RgogugjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rgogugj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rgogugj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'revendicationRepository' => ['privates', 'App\\Repository\\RevendicationRepository', 'getRevendicationRepositoryService', true],
        ], [
            'revendicationRepository' => 'App\\Repository\\RevendicationRepository',
        ]);
    }
}
