<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container51wFsbP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container51wFsbP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container51wFsbP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container51wFsbP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container51wFsbP\App_KernelDevDebugContainer([
    'container.build_hash' => '51wFsbP',
    'container.build_id' => '2cb60fb1',
    'container.build_time' => 1759760711,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container51wFsbP');
