<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAZmwlXb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAZmwlXb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAZmwlXb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAZmwlXb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAZmwlXb\App_KernelDevDebugContainer([
    'container.build_hash' => 'AZmwlXb',
    'container.build_id' => 'ed60004f',
    'container.build_time' => 1759757031,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAZmwlXb');
